### ISSUE TITLE
Failed to set language: en and country: en-US (Selenium::WebDriver::Error::UnknownError)

### ISSUE THREAD

**Issue by ankurgupta2817** [isonic1/Appium-Native-Crawler#4]
Hi Justin, Facing below issue. Please suggest how to proceed

![image](https://user-images.githubusercontent.com/16332452/60315814-cff2b280-9985-11e9-81a7-ce0e667e2023.png)

**Appium Logs:**

/Users/ankurgupta/.rvm/gems/ruby-2.6.3/gems/aaet-0.1.0/lib/aaet/android/parser.rb:10: warning: circular argument reference - driver

Clearing Redis DB..

App Activities: 
[
    [0] ".Activities.MainActivity",
    [1] ".Activities.BackNavigationActivity",
    [2] ".Activities.UpNavigationActivity"
]

Testing Languages: ["en"]
Running Language: en
@program_opts: {:activities=>[".Activities.MainActivity", ".Activities.BackNavigationActivity", ".Activities.UpNavigationActivity"], :options=>{:mode=>"crawler", :emulator=>["Pixel_API_24"], :orientation=>"PORTRAIT", :language=>["en"], :uuid=>nil, :keepEmulatorAlive=>false, :bothOrientations=>false, :translate=>false, :applitools=>false, :updateBaseline=>false, :debug=>true, :resetAppium=>false, :cloud=>false, :seconds=>300, :config=>"app-debug.txt"}, :config=>{:caps=>{:caps=>{:platformName=>"ANDROID", :platform=>"android", :deviceName=>"android", :app=>"./app-debug.apk", :zippedApp=>"./app-debug.apk.zip", :url=>"http://localhost:4723/wd/hub", :appPackage=>"com.amazonaws.devicefarm.android.referenceapp", :newCommandTimeout=>"9999", :locale=>"en-US", :orientation=>"PORTRAIT", :language=>"en"}, :avd=>"Pixel_API_24", :appium_lib=>{:server_url=>"http://localhost:4723/wd/hub", :wait=>0}}, :cloud=>{:service=>"saucelabs", :user=>"", :key=>"", :caps_path=>"./sauce-caps.txt"}, :settings=>{:click_count=>3, :google_translate_key=>""}, :homeActivity=>{:activity=>".Activities.MainActivity"}, :backLocators=>[{:hamburger_button=>{:id=>"ReferenceApp"}}], :multiClickLocators=>[{:hamburger_button=>{:id=>"ReferenceApp"}}], :loginPage=>{}, :doNotClick=>[{:crash_button=>{:id=>"com.amazonaws.devicefarm.android.referenceapp:id/crash_button"}}], :applitools=>[{:key=>"", :do_not_upload=>{:id=>"com.amazonaws.devicefarm.android.referenceapp:id/drawer_row_icon"}, :home_page=>{:activity=>".Activities.MainActivity", :id=>"Homepage Headline", :text=>"Homepage"}, :component_page=>{:activity=>".Activities.MainActivity", :id=>"com.amazonaws.devicefarm.android.referenceapp:id/native_image_grid_view", :text=>"Native Components"}, :alert_page=>{:activity=>".Activities.MainActivity", :id=>"com.amazonaws.devicefarm.android.referenceapp:id/notifications_alert_button", :text=>"ALERT"}, :alert_popup=>{:activity=>".Activities.MainActivity", :id=>"android:id/alertTitle", :text=>"Alert Title"}, :navigation_page=>{:activity=>".Activities.BackNavigationActivity", :id=>"com.amazonaws.devicefarm.android.referenceapp:id/back_navigation_counter", :text=>"2"}}]}, :run_time=>"2019.06.28.09.18", :output_dir_base=>"output/2019.06.28.09.18", :process=>0}
@activities: [".Activities.MainActivity", ".Activities.BackNavigationActivity", ".Activities.UpNavigationActivity"]
@options_mode: crawler
@options_emulator: ["Pixel_API_24"]
@options_orientation: PORTRAIT
@options_language: ["en"]
@options_uuid: 
@options_keepEmulatorAlive: false
@options_bothOrientations: false
@options_translate: false
@options_applitools: false
@options_updateBaseline: false
@options_debug: true
@options_resetAppium: false
@options_cloud: false
@options_seconds: 300
@options_config: app-debug.txt
@options: {:mode=>"crawler", :emulator=>["Pixel_API_24"], :orientation=>"PORTRAIT", :language=>["en"], :uuid=>nil, :keepEmulatorAlive=>false, :bothOrientations=>false, :translate=>false, :applitools=>false, :updateBaseline=>false, :debug=>true, :resetAppium=>false, :cloud=>false, :seconds=>300, :config=>"app-debug.txt"}
@caps_platformName: ANDROID
@caps_platform: android
@caps_deviceName: android
@caps_app: ./app-debug.apk
@caps_zippedApp: ./app-debug.apk.zip
@caps_url: http://localhost:4723/wd/hub
@caps_appPackage: com.amazonaws.devicefarm.android.referenceapp
@caps_newCommandTimeout: 9999
@caps_locale: en-US
@caps_orientation: PORTRAIT
@caps_language: en
@caps: {:caps=>{:platformName=>"ANDROID", :platform=>"android", :deviceName=>"android", :app=>"./app-debug.apk", :zippedApp=>"./app-debug.apk.zip", :url=>"http://localhost:4723/wd/hub", :appPackage=>"com.amazonaws.devicefarm.android.referenceapp", :newCommandTimeout=>"9999", :locale=>"en-US", :orientation=>"PORTRAIT", :language=>"en"}, :avd=>"Pixel_API_24", :appium_lib=>{:server_url=>"http://localhost:4723/wd/hub", :wait=>0}}
@caps_avd: Pixel_API_24
@appium_lib_server_url: http://localhost:4723/wd/hub
@appium_lib_wait: 0
@appium_lib: {:server_url=>"http://localhost:4723/wd/hub", :wait=>0}
@cloud_service: saucelabs
@cloud_user: 
@cloud_key: 
@cloud_caps_path: ./sauce-caps.txt
@cloud: {:service=>"saucelabs", :user=>"", :key=>"", :caps_path=>"./sauce-caps.txt"}
@settings_click_count: 3
@settings_google_translate_key: 
@settings: {:click_count=>3, :google_translate_key=>""}
@homeActivity_activity: .Activities.MainActivity
@homeActivity: {:activity=>".Activities.MainActivity"}
@config_backLocators: [{:hamburger_button=>{:id=>"ReferenceApp"}}]
@config_multiClickLocators: [{:hamburger_button=>{:id=>"ReferenceApp"}}]
@loginPage: {}
@config_doNotClick: [{:crash_button=>{:id=>"com.amazonaws.devicefarm.android.referenceapp:id/crash_button"}}]
@config_applitools: [{:key=>"", :do_not_upload=>{:id=>"com.amazonaws.devicefarm.android.referenceapp:id/drawer_row_icon"}, :home_page=>{:activity=>".Activities.MainActivity", :id=>"Homepage Headline", :text=>"Homepage"}, :component_page=>{:activity=>".Activities.MainActivity", :id=>"com.amazonaws.devicefarm.android.referenceapp:id/native_image_grid_view", :text=>"Native Components"}, :alert_page=>{:activity=>".Activities.MainActivity", :id=>"com.amazonaws.devicefarm.android.referenceapp:id/notifications_alert_button", :text=>"ALERT"}, :alert_popup=>{:activity=>".Activities.MainActivity", :id=>"android:id/alertTitle", :text=>"Alert Title"}, :navigation_page=>{:activity=>".Activities.BackNavigationActivity", :id=>"com.amazonaws.devicefarm.android.referenceapp:id/back_navigation_counter", :text=>"2"}}]
@config: {:caps=>{:caps=>{:platformName=>"ANDROID", :platform=>"android", :deviceName=>"android", :app=>"./app-debug.apk", :zippedApp=>"./app-debug.apk.zip", :url=>"http://localhost:4723/wd/hub", :appPackage=>"com.amazonaws.devicefarm.android.referenceapp", :newCommandTimeout=>"9999", :locale=>"en-US", :orientation=>"PORTRAIT", :language=>"en"}, :avd=>"Pixel_API_24", :appium_lib=>{:server_url=>"http://localhost:4723/wd/hub", :wait=>0}}, :cloud=>{:service=>"saucelabs", :user=>"", :key=>"", :caps_path=>"./sauce-caps.txt"}, :settings=>{:click_count=>3, :google_translate_key=>""}, :homeActivity=>{:activity=>".Activities.MainActivity"}, :backLocators=>[{:hamburger_button=>{:id=>"ReferenceApp"}}], :multiClickLocators=>[{:hamburger_button=>{:id=>"ReferenceApp"}}], :loginPage=>{}, :doNotClick=>[{:crash_button=>{:id=>"com.amazonaws.devicefarm.android.referenceapp:id/crash_button"}}], :applitools=>[{:key=>"", :do_not_upload=>{:id=>"com.amazonaws.devicefarm.android.referenceapp:id/drawer_row_icon"}, :home_page=>{:activity=>".Activities.MainActivity", :id=>"Homepage Headline", :text=>"Homepage"}, :component_page=>{:activity=>".Activities.MainActivity", :id=>"com.amazonaws.devicefarm.android.referenceapp:id/native_image_grid_view", :text=>"Native Components"}, :alert_page=>{:activity=>".Activities.MainActivity", :id=>"com.amazonaws.devicefarm.android.referenceapp:id/notifications_alert_button", :text=>"ALERT"}, :alert_popup=>{:activity=>".Activities.MainActivity", :id=>"android:id/alertTitle", :text=>"Alert Title"}, :navigation_page=>{:activity=>".Activities.BackNavigationActivity", :id=>"com.amazonaws.devicefarm.android.referenceapp:id/back_navigation_counter", :text=>"2"}}]}
@run_time: 2019.06.28.09.18
@output_dir_base: output/2019.06.28.09.18
@process: 0
@platform_setup: #<AndroidSetup:0x00007fa61b6c8928>
@appium_arg: --avd Pixel_API_24
@appium_reset: --no-reset
Traceback (most recent call last):
	47: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/import.rb:5:in `block in <top (required)>'
	46: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
	45: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
	44: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
	43: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
	42: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
	41: from /Users/ankurgupta/.rvm/gems/ruby-2.6.3/gems/aaet-0.1.0/bin/aaet:62:in `block (2 levels) in <top (required)>'
	40: from /Users/ankurgupta/.rvm/gems/ruby-2.6.3/gems/aaet-0.1.0/run.rb:211:in `crawler'
	39: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:203:in `each'
	38: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:241:in `map'
	37: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:327:in `work_in_processes'
	36: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:385:in `create_workers'
	35: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:385:in `each_with_index'
	34: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:385:in `each'
	33: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:386:in `block in create_workers'
	32: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:395:in `worker'
	31: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:395:in `fork'
	30: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:404:in `block in worker'
	29: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:422:in `process_incoming_jobs'
	28: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/parallel-1.9.0/lib/parallel.rb:453:in `call_with_index'
	27: from /Users/ankurgupta/.rvm/gems/ruby-2.6.3/gems/aaet-0.1.0/run.rb:223:in `block in crawler'
	26: from /Users/ankurgupta/.rvm/gems/ruby-2.6.3/gems/aaet-0.1.0/run.rb:223:in `each'
	25: from /Users/ankurgupta/.rvm/gems/ruby-2.6.3/gems/aaet-0.1.0/run.rb:226:in `block (2 levels) in crawler'
	24: from /Users/ankurgupta/.rvm/gems/ruby-2.6.3/gems/aaet-0.1.0/run.rb:90:in `runner'
	23: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
	22: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
	21: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
	20: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
	19: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	18: from /Users/ankurgupta/.rvm/gems/ruby-2.6.3/gems/aaet-0.1.0/run.rb:90:in `block in runner'
	17: from /Users/ankurgupta/.rvm/gems/ruby-2.6.3/gems/aaet-0.1.0/run.rb:161:in `go'
	16: from /Users/ankurgupta/.rvm/gems/ruby-2.6.3/gems/aaet-0.1.0/run.rb:127:in `initialize_driver'
	15: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/appium_lib-10.3.1/lib/appium_lib/driver.rb:548:in `start_driver'
	14: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/appium_lib_core-3.1.3/lib/appium_lib_core/driver.rb:348:in `start_driver'
	13: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/appium_lib_core-3.1.3/lib/appium_lib_core/driver.rb:348:in `new'
	12: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/appium_lib_core-3.1.3/lib/appium_lib_core/common/base/driver.rb:34:in `initialize'
	11: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/appium_lib_core-3.1.3/lib/appium_lib_core/common/base/bridge.rb:47:in `handshake'
	10: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/appium_lib_core-3.1.3/lib/appium_lib_core/common/base/bridge.rb:107:in `create_session'
	 9: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
	 8: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/appium_lib_core-3.1.3/lib/appium_lib_core/common/base/http_default.rb:81:in `call'
	 7: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
	 6: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
	 5: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
	 4: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	 3: from /Users/ankurgupta/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
	 2: from     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)
	 1: from     at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to set language: en and country: en-US: An unknown server-side error occurred while processing the command. Original error: Failed to set language: en and country: en-US (Selenium::WebDriver::Error::UnknownError)

**Comment by isonic1** [comment]
Hi @ankurgupta2817 in the app-debug.txt, please set the capability for locale  = "en" instead of "en-US". There was a past appium version that changed this behavior. Let me know if that resolves it for you. Thanks.
